import { SelectOption } from '../../../../../shared/ui/form-input/models/form-config.model';

export enum TradeBotTextKey {
  StrategyListTitle = 'tradeBot.strategy.list.title',
  NewStrategy = 'tradeBot.strategy.actions.new',
  RunBacktest = 'tradeBot.strategy.actions.runBacktest',
  Backtest = 'tradeBot.strategy.actions.backtest',
  CreateStrategyTitle = 'tradeBot.strategy.form.createTitle',
  EditStrategyTitle = 'tradeBot.strategy.form.editTitle',
  SaveStrategy = 'tradeBot.strategy.form.save',
  GeneralInformation = 'tradeBot.strategy.section.general.title',
  GeneralInformationDesc = 'tradeBot.strategy.section.general.description',
  StrategyConfiguration = 'tradeBot.strategy.section.config.title',
  StrategyConfigurationDesc = 'tradeBot.strategy.section.config.description',
  RiskReward = 'tradeBot.strategy.section.riskReward.title',
  RiskRewardDesc = 'tradeBot.strategy.section.riskReward.description',
  FormGuide = 'tradeBot.strategy.section.guide.title',
  FormGuideDesc = 'tradeBot.strategy.section.guide.description',
  RouteSourceOfTruth = 'tradeBot.strategy.form.routeSourceOfTruth',
  ValidationSummary = 'tradeBot.strategy.form.validationSummary',
  BacktestDefaults = 'tradeBot.strategy.form.backtestDefaults',
  BacktestDefaultsDesc = 'tradeBot.strategy.form.backtestDefaultsDescription',
  GeneralInformationReady = 'tradeBot.strategy.form.validation.generalReady',
  GeneralInformationNeedsReview = 'tradeBot.strategy.form.validation.generalNeedsReview',
  ConfigReady = 'tradeBot.strategy.form.validation.configReady',
  ConfigNeedsReview = 'tradeBot.strategy.form.validation.configNeedsReview',
  RiskReady = 'tradeBot.strategy.form.validation.riskReady',
  RiskNeedsReview = 'tradeBot.strategy.form.validation.riskNeedsReview',
  BindingName = 'tradeBot.strategy.field.bindingName',
  StrategyCode = 'tradeBot.strategy.field.strategyCode',
  StrategyName = 'tradeBot.strategy.field.strategyName',
  Exchange = 'tradeBot.strategy.field.exchange',
  Symbol = 'tradeBot.strategy.field.symbol',
  MarketType = 'tradeBot.strategy.field.marketType',
  TradeSideMode = 'tradeBot.strategy.field.tradeSideMode',
  ProviderSymbol = 'tradeBot.strategy.field.providerSymbol',
  Description = 'tradeBot.strategy.field.description',
  Status = 'tradeBot.strategy.field.status',
  Timezone = 'tradeBot.strategy.field.timezone',
  BaseTimeframe = 'tradeBot.strategy.field.baseTimeframe',
  TriggerTimeframe = 'tradeBot.strategy.field.triggerTimeframe',
  EntryMode = 'tradeBot.strategy.field.entryMode',
  StopLossMode = 'tradeBot.strategy.field.stopLossMode',
  TakeProfitRr = 'tradeBot.strategy.field.takeProfitRr',
  MaxTradesPerDay = 'tradeBot.strategy.field.maxTradesPerDay',
  StrategyValidity = 'tradeBot.strategy.field.strategyValidity',
  FirstM15Start = 'tradeBot.strategy.field.firstM15Start',
  BreakoutConfirmByClose = 'tradeBot.strategy.field.breakoutConfirmByClose',
  SessionStart = 'tradeBot.strategy.field.sessionStart',
  SessionEnd = 'tradeBot.strategy.field.sessionEnd',
  RangeMinutes = 'tradeBot.strategy.field.rangeMinutes',
  RetestWindowCandles = 'tradeBot.strategy.field.retestWindowCandles',
  TrendEmaPeriod = 'tradeBot.strategy.field.trendEmaPeriod',
  PullbackEmaPeriod = 'tradeBot.strategy.field.pullbackEmaPeriod',
  ChannelLookback = 'tradeBot.strategy.field.channelLookback',
  AtrPeriod = 'tradeBot.strategy.field.atrPeriod',
  AtrSlMultiplier = 'tradeBot.strategy.field.atrSlMultiplier',
  BbPeriod = 'tradeBot.strategy.field.bbPeriod',
  BbStdDev = 'tradeBot.strategy.field.bbStdDev',
  RsiPeriod = 'tradeBot.strategy.field.rsiPeriod',
  RsiOverbought = 'tradeBot.strategy.field.rsiOverbought',
  RsiOversold = 'tradeBot.strategy.field.rsiOversold',
  SupportResistanceLookback = 'tradeBot.strategy.field.supportResistanceLookback',
  ZoneAtrMultiplier = 'tradeBot.strategy.field.zoneAtrMultiplier',
  MinDistanceFromVwapPct = 'tradeBot.strategy.field.minDistanceFromVwapPct',
  AsiaStart = 'tradeBot.strategy.field.asiaStart',
  AsiaEnd = 'tradeBot.strategy.field.asiaEnd',
  LondonStart = 'tradeBot.strategy.field.londonStart',
  MotherBarLookback = 'tradeBot.strategy.field.motherBarLookback',
  PivotLeft = 'tradeBot.strategy.field.pivotLeft',
  PivotRight = 'tradeBot.strategy.field.pivotRight',
  MinBarsBetweenPivots = 'tradeBot.strategy.field.minBarsBetweenPivots',
  MaxBarsBetweenPivots = 'tradeBot.strategy.field.maxBarsBetweenPivots',
  LiquidityLookback = 'tradeBot.strategy.field.liquidityLookback',
  FvgMinGapRatio = 'tradeBot.strategy.field.fvgMinGapRatio',
  ReclaimWindowCandles = 'tradeBot.strategy.field.reclaimWindowCandles',
  ChooseStrategyType = 'tradeBot.strategy.typePicker.title',
  ChooseStrategyTypeDesc = 'tradeBot.strategy.typePicker.description',
  SearchStrategyPlaceholder = 'tradeBot.strategy.typePicker.searchPlaceholder',
  StrategyRouteDesc = 'tradeBot.strategy.typePicker.routeDescription',
  SaveStrategyFailed = 'tradeBot.strategy.toast.saveFailed',
  SaveStrategySuccess = 'tradeBot.strategy.toast.saveSuccess',
  UpdateStrategySuccess = 'tradeBot.strategy.toast.updateSuccess',
  DeleteStrategySuccess = 'tradeBot.strategy.toast.deleteSuccess',
  DeleteStrategyFailed = 'tradeBot.strategy.toast.deleteFailed',
  LoadStrategyFormFailed = 'tradeBot.strategy.toast.loadFormFailed',
  LoadStrategyListFailed = 'tradeBot.strategy.toast.loadListFailed',
  ReviewStrategyBeforeSave = 'tradeBot.strategy.toast.reviewBeforeSave',
  LoadStrategyTypesFailed = 'tradeBot.strategy.toast.loadTypesFailed',
  BacktestReplayTitle = 'tradeBot.replay.title',
  BacktestExecution = 'tradeBot.replay.execution.title',
  BacktestExecutionDesc = 'tradeBot.replay.execution.description',
  TotalTrades = 'tradeBot.replay.metric.totalTrades',
  WinTrades = 'tradeBot.replay.metric.winTrades',
  LoseTrades = 'tradeBot.replay.metric.loseTrades',
  WinRate = 'tradeBot.replay.metric.winRate',
  Pnl = 'tradeBot.replay.metric.pnl',
  FinalEquity = 'tradeBot.replay.metric.finalEquity',
  InitialBalance = 'tradeBot.replay.field.initialBalance',
  FeeRate = 'tradeBot.replay.field.feeRate',
  Slippage = 'tradeBot.replay.field.slippage',
  RiskPerTrade = 'tradeBot.replay.field.riskPerTrade',
  TradeDate = 'tradeBot.replay.field.tradeDate',
  Side = 'tradeBot.replay.field.side',
  EntryTime = 'tradeBot.replay.field.entryTime',
  EntryPrice = 'tradeBot.replay.field.entryPrice',
  StopLossPrice = 'tradeBot.replay.field.stopLossPrice',
  TakeProfitPrice = 'tradeBot.replay.field.takeProfitPrice',
  ExitTime = 'tradeBot.replay.field.exitTime',
  ExitPrice = 'tradeBot.replay.field.exitPrice',
  Result = 'tradeBot.replay.field.result',
  RrAchieved = 'tradeBot.replay.field.rrAchieved',
  EntryReason = 'tradeBot.replay.field.entryReason',
  ExitReason = 'tradeBot.replay.field.exitReason',
  WinLoss = 'tradeBot.replay.field.winLoss',
  SlFirstRule = 'tradeBot.replay.execution.slFirstRule',
  ReplayChart = 'tradeBot.replay.chart.title',
  ReplayChartDesc = 'tradeBot.replay.chart.description',
  BacktestOrders = 'tradeBot.replay.orders.title',
  BacktestOrdersDesc = 'tradeBot.replay.orders.description',
  StepExplanation = 'tradeBot.replay.step.title',
  StepExplanationDesc = 'tradeBot.replay.step.description',
  EventLog = 'tradeBot.replay.eventLog.title',
  EventLogDesc = 'tradeBot.replay.eventLog.description',
  TradeTimeline = 'tradeBot.replay.tradeTimeline.title',
  TradeTimelineDesc = 'tradeBot.replay.tradeTimeline.description',
  AutoPause = 'tradeBot.replay.autoPause.title',
  AutoPauseDesc = 'tradeBot.replay.autoPause.description',
  Rules = 'tradeBot.replay.step.rules',
  Events = 'tradeBot.replay.step.events',
  NoEventOnStep = 'tradeBot.replay.step.noEvent',
  ReplayEmpty = 'tradeBot.replay.step.empty',
  NoEventDetail = 'tradeBot.replay.eventLog.noDetail',
  NoEventMessage = 'tradeBot.replay.step.noEventMessage',
  ActiveTrade = 'tradeBot.replay.step.activeTrade',
  PrevEvent = 'tradeBot.replay.controls.prevEvent',
  NextEvent = 'tradeBot.replay.controls.nextEvent',
  Speed = 'tradeBot.replay.controls.speed',
  Step = 'tradeBot.replay.controls.step',
  RunBacktestFailed = 'tradeBot.replay.toast.runFailed',
  RunBacktestSuccess = 'tradeBot.replay.toast.runSuccess',
  LoadBindingFailed = 'tradeBot.replay.toast.loadBindingFailed',
  LoadReplayFailed = 'tradeBot.replay.toast.loadReplayFailed',
  ReviewBacktestBeforeRun = 'tradeBot.replay.toast.reviewBeforeRun',
  OptionMarketTypeCrypto = 'tradeBot.option.marketType.crypto',
  OptionMarketTypeForex = 'tradeBot.option.marketType.forex',
  OptionMarketTypeMetal = 'tradeBot.option.marketType.metal',
  OptionTradeSideBoth = 'tradeBot.option.tradeSide.both',
  OptionTradeSideLongOnly = 'tradeBot.option.tradeSide.longOnly',
  OptionTradeSideShortOnly = 'tradeBot.option.tradeSide.shortOnly',
  OptionEntryModeNextCandleOpen = 'tradeBot.option.entryMode.nextCandleOpen',
  OptionEntryModeCurrentCandleClose = 'tradeBot.option.entryMode.currentCandleClose',
  OptionEntryModeLimitRetest = 'tradeBot.option.entryMode.limitRetest',
  OptionSlModeFirstCandleMidRange = 'tradeBot.option.slMode.firstCandleMidRange',
  OptionSlModeSwing = 'tradeBot.option.slMode.swing',
  OptionSlModeAtr = 'tradeBot.option.slMode.atr',
  OptionSlModeMotherBar = 'tradeBot.option.slMode.motherBar',
  OptionSlModeVwap = 'tradeBot.option.slMode.vwap',
  OptionValiditySameNewYorkDay = 'tradeBot.option.validity.sameNewYorkDay',
  OptionValiditySameSession = 'tradeBot.option.validity.sameSession',
  OptionValidityUntilInvalidated = 'tradeBot.option.validity.untilInvalidated',
  OptionTimezoneUtc = 'tradeBot.option.timezone.utc',
  OptionTimezoneNewYork = 'tradeBot.option.timezone.newYork',
  OptionTimezoneLondon = 'tradeBot.option.timezone.london',
  OptionTimezoneTokyo = 'tradeBot.option.timezone.tokyo',
  OptionTimeframeM1 = 'tradeBot.option.timeframe.m1',
  OptionTimeframeM5 = 'tradeBot.option.timeframe.m5',
  OptionTimeframeM15 = 'tradeBot.option.timeframe.m15',
  OptionTimeframeM30 = 'tradeBot.option.timeframe.m30',
  OptionTimeframeH1 = 'tradeBot.option.timeframe.h1',
  OptionTimeframeH4 = 'tradeBot.option.timeframe.h4',
  OptionTimeframeD1 = 'tradeBot.option.timeframe.d1',
  OptionReplayEventSetupFormed = 'tradeBot.option.replayEvent.setupFormed',
  OptionReplayEventConditionMatched = 'tradeBot.option.replayEvent.conditionMatched',
  OptionReplayEventOrderPlaced = 'tradeBot.option.replayEvent.orderPlaced',
  OptionReplayEventSlHit = 'tradeBot.option.replayEvent.slHit',
  OptionReplayEventTpHit = 'tradeBot.option.replayEvent.tpHit',
  OptionReplayEventTradeClosed = 'tradeBot.option.replayEvent.tradeClosed',
  OptionReplayEventSessionStarted = 'tradeBot.option.replayEvent.sessionStarted',
  OptionReplayEventSessionEnded = 'tradeBot.option.replayEvent.sessionEnded',
  OptionReplayEventRulePass = 'tradeBot.option.replayEvent.rulePass',
  OptionReplayEventRuleFail = 'tradeBot.option.replayEvent.ruleFail'
}

export enum StrategyEntryMode {
  NEXT_CANDLE_OPEN = 'NEXT_CANDLE_OPEN',
  CURRENT_CANDLE_CLOSE = 'CURRENT_CANDLE_CLOSE',
  LIMIT_RETEST = 'LIMIT_RETEST'
}

export enum StrategyStopLossMode {
  FIRST_CANDLE_MID_RANGE = 'FIRST_CANDLE_MID_RANGE',
  SWING = 'SWING',
  ATR = 'ATR',
  MOTHER_BAR = 'MOTHER_BAR',
  VWAP = 'VWAP'
}

export enum StrategyValidityMode {
  SAME_NEW_YORK_DAY = 'SAME_NEW_YORK_DAY',
  SAME_SESSION = 'SAME_SESSION',
  UNTIL_INVALIDATED = 'UNTIL_INVALIDATED'
}

export enum StrategyTimezone {
  UTC = 'UTC',
  AMERICA_NEW_YORK = 'America/New_York',
  EUROPE_LONDON = 'Europe/London',
  ASIA_TOKYO = 'Asia/Tokyo'
}

export enum StrategyTimeframe {
  M1 = 'M1',
  M5 = 'M5',
  M15 = 'M15',
  M30 = 'M30',
  H1 = 'H1',
  H4 = 'H4',
  D1 = 'D1'
}

export const STRATEGY_TIMEZONE_OPTIONS: SelectOption[] = [
  { label: TradeBotTextKey.OptionTimezoneUtc, value: StrategyTimezone.UTC },
  { label: TradeBotTextKey.OptionTimezoneNewYork, value: StrategyTimezone.AMERICA_NEW_YORK },
  { label: TradeBotTextKey.OptionTimezoneLondon, value: StrategyTimezone.EUROPE_LONDON },
  { label: TradeBotTextKey.OptionTimezoneTokyo, value: StrategyTimezone.ASIA_TOKYO }
];

export const STRATEGY_TIMEFRAME_OPTIONS: SelectOption[] = [
  { label: TradeBotTextKey.OptionTimeframeM1, value: StrategyTimeframe.M1 },
  { label: TradeBotTextKey.OptionTimeframeM5, value: StrategyTimeframe.M5 },
  { label: TradeBotTextKey.OptionTimeframeM15, value: StrategyTimeframe.M15 },
  { label: TradeBotTextKey.OptionTimeframeM30, value: StrategyTimeframe.M30 },
  { label: TradeBotTextKey.OptionTimeframeH1, value: StrategyTimeframe.H1 },
  { label: TradeBotTextKey.OptionTimeframeH4, value: StrategyTimeframe.H4 },
  { label: TradeBotTextKey.OptionTimeframeD1, value: StrategyTimeframe.D1 }
];

export const STRATEGY_ENTRY_MODE_OPTIONS: SelectOption[] = [
  { label: TradeBotTextKey.OptionEntryModeNextCandleOpen, value: StrategyEntryMode.NEXT_CANDLE_OPEN },
  { label: TradeBotTextKey.OptionEntryModeCurrentCandleClose, value: StrategyEntryMode.CURRENT_CANDLE_CLOSE },
  { label: TradeBotTextKey.OptionEntryModeLimitRetest, value: StrategyEntryMode.LIMIT_RETEST }
];

export const STRATEGY_SL_MODE_OPTIONS: SelectOption[] = [
  { label: TradeBotTextKey.OptionSlModeFirstCandleMidRange, value: StrategyStopLossMode.FIRST_CANDLE_MID_RANGE },
  { label: TradeBotTextKey.OptionSlModeSwing, value: StrategyStopLossMode.SWING },
  { label: TradeBotTextKey.OptionSlModeAtr, value: StrategyStopLossMode.ATR },
  { label: TradeBotTextKey.OptionSlModeMotherBar, value: StrategyStopLossMode.MOTHER_BAR },
  { label: TradeBotTextKey.OptionSlModeVwap, value: StrategyStopLossMode.VWAP }
];

export const STRATEGY_VALIDITY_OPTIONS: SelectOption[] = [
  { label: TradeBotTextKey.OptionValiditySameNewYorkDay, value: StrategyValidityMode.SAME_NEW_YORK_DAY },
  { label: TradeBotTextKey.OptionValiditySameSession, value: StrategyValidityMode.SAME_SESSION },
  { label: TradeBotTextKey.OptionValidityUntilInvalidated, value: StrategyValidityMode.UNTIL_INVALIDATED }
];

export const REPLAY_EVENT_TYPE_OPTIONS: SelectOption[] = [
  { label: TradeBotTextKey.OptionReplayEventSetupFormed, value: 'setup-formed' },
  { label: TradeBotTextKey.OptionReplayEventConditionMatched, value: 'condition-matched' },
  { label: TradeBotTextKey.OptionReplayEventOrderPlaced, value: 'order-placed' },
  { label: TradeBotTextKey.OptionReplayEventSlHit, value: 'sl-hit' },
  { label: TradeBotTextKey.OptionReplayEventTpHit, value: 'tp-hit' },
  { label: TradeBotTextKey.OptionReplayEventTradeClosed, value: 'trade-closed' },
  { label: TradeBotTextKey.OptionReplayEventSessionStarted, value: 'session-started' },
  { label: TradeBotTextKey.OptionReplayEventSessionEnded, value: 'session-ended' },
  { label: TradeBotTextKey.OptionReplayEventRulePass, value: 'rule-pass' },
  { label: TradeBotTextKey.OptionReplayEventRuleFail, value: 'rule-fail' }
];
