apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["/busybox/sh"]
      args: ["-c", "sleep 1500"]
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: kubectl
      image: lamld2510/kubectl
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          sleep infinity

      volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: node
      image: node:20-alpine
      command: ["sh"]
      args: ["-c", "sleep 1500"]
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: npm-cache
          mountPath: /root/.npm
      resources:
        requests:
          cpu: "1000m"
          memory: "2Gi"

  volumes:
    - name: docker-config
      projected:
        sources:
          - secret:
              name: docker-config
    - name: kubeconfig
      secret:
        secretName: kubeconfig-jenkins
    - name: workspace-volume
      emptyDir: {}
    - name: npm-cache
      persistentVolumeClaim:
        claimName: npm-cache-pvc
